require:
  - rubocop-rails

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - spec\models\game_session_spec.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false